logs:
  - name: root
    level: info
    formatter: '%d%T%m%n'
    appenders:
      - type: FileLogAppender
        file: root.txt
      - type: StdoutLogAppender
  - name: system
    level: debug
    formatter: '%d%T%m%n'
    appenders:
      - type: FileLogAppender
        formatter: "%d%T[%p]%T%m%n"
        file: system.txt
      - type: StdoutLogAppender
system:
  port: 9900
  value: 15
  int_vec:
    - 10
    - 20
    - 30
  int_list: [20, 40, 50]
  int_set: [30, 20, 60, 20]
  int_uset: [40, 60, 50, 20]
  str_int_map:
    k: 30
    v: 20
  str_int_umap:
    k1: 130
    k2: 110
    k3: 120
class:
  person:
    name: cool
    age: 1
    sex: 1
